"""
Report Agent — Generates structured, professional Markdown reports from data/context.
Uses a chain-of-thought approach to produce executive-quality output.
"""

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_openai import ChatOpenAI
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_groq import ChatGroq
from loguru import logger

from backend.config import get_settings

settings = get_settings()

_REPORT_SYSTEM = """You are a senior business analyst and professional report writer.
Your reports are used by C-suite executives and must be:
- **Accurate**: Based only on provided data — never fabricate facts
- **Structured**: Use clear headings, bullet points, and tables
- **Actionable**: End with specific, prioritized recommendations
- **Concise**: Executive summaries under 100 words; full report 500-1500 words

Report structure to follow:
# [Report Title]
**Date:** [current date]
**Prepared for:** [audience if specified]

## Executive Summary
[3-5 sentences covering the most important points]

## Key Findings
- Finding 1
- Finding 2
...

## Detailed Analysis
[Subsections with headers, data tables, observations]

## Recommendations
1. [Most important action — High Priority]
2. [Second action — Medium Priority]
...

## Conclusion
[Brief closing paragraph]

---
*This report was generated by Enterprise AI Assistant*"""


def _get_llm():
    if settings.default_llm_provider == "openai":
        return ChatOpenAI(
            model="gpt-4o",
            temperature=0.3,
            openai_api_key=settings.openai_api_key,
        )
    elif settings.default_llm_provider == "groq":
        return ChatGroq(
            model="llama-3.3-70b-versatile",
            temperature=0.3,
            groq_api_key=settings.groq_api_key,
        )
    return ChatGoogleGenerativeAI(
        model="gemini-1.5-pro",
        temperature=0.3,
        google_api_key=settings.google_api_key,
    )


def create_report_chain():
    """
    Build a report generation chain.

    Invoke with:
        chain.invoke({
            "topic": "Q1 Sales Performance",
            "context": "Sales data: ...",
            "audience": "Board of Directors",
            "format_instructions": "Include revenue tables"
        })

    Returns:
        LangChain chain that outputs a Markdown report string
    """
    llm = _get_llm()

    prompt = ChatPromptTemplate.from_messages([
        ("system", _REPORT_SYSTEM),
        ("human",
         "Generate a comprehensive report on the following:\n\n"
         "**Topic:** {topic}\n\n"
         "**Target Audience:** {audience}\n\n"
         "**Data & Context:**\n{context}\n\n"
         "**Special Instructions:** {format_instructions}"
        ),
    ])

    chain = prompt | llm | StrOutputParser()
    logger.info("Report chain created")
    return chain


def create_summary_chain():
    """
    Build a quick summarization chain.
    Useful for summarizing long documents, search results, or conversations.

    Invoke with:
        chain.invoke({"content": "...", "max_words": 150})
    """
    llm = _get_llm()

    prompt = ChatPromptTemplate.from_messages([
        ("system",
         "You are a concise summarizer. Summarize the given content clearly and accurately. "
         "Preserve all key facts, numbers, and conclusions. "
         "Do not add information not present in the source."
        ),
        ("human",
         "Summarize the following content in approximately {max_words} words:\n\n{content}"
        ),
    ])

    chain = prompt | llm | StrOutputParser()
    return chain


# Pre-built instances
report_chain = create_report_chain()
summary_chain = create_summary_chain()
